// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID     string `json:"id" bson:"_id,omitempty"`
	Text   string `json:"text" bson:"text,omitempty"`
	Done   bool   `json:"done" bson:"done,omitempty"`
	UserID string `json:"userId" bson:"userId,omitempty"`
}

type User struct {
	ID       string `json:"id" bson:"_id,omitempty"`
	Username string `json:"username" bson:"username,omitempty"`
}
