// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Affiliation struct {
	ID string `json:"id" bson:"_id,omitempty"`
}

func (Affiliation) IsEntity() {}

type Customer struct {
	ID string `json:"id" bson:"_id,omitempty"`
}

func (Customer) IsEntity() {}

type Mutation struct {
}

type Query struct {
}

type Response struct {
	Status  bool   `json:"status" bson:"status,omitempty"`
	Message string `json:"message" bson:"message,omitempty"`
}

type User struct {
	ID          string       `json:"id" bson:"_id,omitempty"`
	Username    string       `json:"username" bson:"username,omitempty"`
	Password    string       `json:"password" bson:"password,omitempty"`
	Customer    *Customer    `json:"customer" bson:"customer,omitempty"`
	Affiliation *Affiliation `json:"affiliation" bson:"affiliation,omitempty"`
}

type UserInput struct {
	ID          *string `json:"id,omitempty"`
	Username    string  `json:"username" bson:"username,omitempty"`
	Password    string  `json:"password" bson:"password,omitempty"`
	Customer    string  `json:"customer" bson:"customer,omitempty"`
	Affiliation string  `json:"affiliation" bson:"affiliation,omitempty"`
}
